### PR TITLE
Adding assembly language and new design.

### PR DESCRIPTION
**Pull request by Abu-Maher**
Adding assembly language.

### CODE REVIEW

**Comment by Zukaritasu** [comment]
It is not necessary to define L_ASSEMBLY since L_ASM is the one that represents assembly
You just have to follow the same example as the other languages

```cpp
case L_ASM: 
    return { "ASSEMBLY", "assembly" };
```

**Comment by Abu-Maher** [comment]
done now?

**Comment by Zukaritasu** [comment]
was already defined

image

**Comment by Abu-Maher** [comment]
what about now?

**Comment by Zukaritasu** [comment]
excellent, that's all

**Pull request merged**
